-- ============================================
-- AUTH PERFORMANCE RPC HELPERS
-- Run this in Supabase SQL Editor
-- ============================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Fast DB-side password verification using pgcrypto.
-- Supports both bcrypt-hashed and temporary plaintext fallback rows.
CREATE OR REPLACE FUNCTION public.auth_login(p_username text, p_password text)
RETURNS TABLE (
  id uuid,
  username text,
  role text,
  "mentorId" text
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT u.id, u.username, u.role, u."mentorId"
  FROM public.users u
  WHERE u.username = p_username
    AND (
      (u.password ~ '^\$2[aby]\$' AND u.password = extensions.crypt(p_password, u.password))
      OR u.password = p_password
    )
  LIMIT 1;
$$;

REVOKE ALL ON FUNCTION public.auth_login(text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.auth_login(text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.auth_login(text, text) TO anon;
GRANT EXECUTE ON FUNCTION public.auth_login(text, text) TO authenticated;

-- DB-side password reset (bcrypt hash generated by Postgres)
CREATE OR REPLACE FUNCTION public.admin_reset_password(p_username text, p_new_password text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.users
  SET password = extensions.crypt(p_new_password, extensions.gen_salt('bf', 12))
  WHERE username = p_username;

  RETURN FOUND;
END;
$$;

REVOKE ALL ON FUNCTION public.admin_reset_password(text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_reset_password(text, text) TO service_role;
